added quotes

diff --git a/bump/_sed_with_prefix b/bump/_sed_with_prefix
--- a/bump/_sed_with_prefix
+++ b/bump/_sed_with_prefix
@@ -12,8 +12,8 @@ for FILE in `find $REPO_PATH -type f`; do
             if [ "$PREFIX" = "$TAG_PREFIX" ]; then
                 echo "found a line to replace content: $LINE_NUMBER in $FILE"
                 let 'LINE_NUMBER++' || echo "let failed"
-                echo running "${LINE_NUMBER}s/(.*)([0-9]+\.[0-9]+\.[0-9]+)(.*)/\1"${VERSION}"\3/g" $FILE
-                sed -i -E "${LINE_NUMBER}s/(.*)([0-9]+\.[0-9]+\.[0-9]+)(.*)/\1${VERSION}\3/g" $FILE || echo "sed failed"
+                echo "running" "${LINE_NUMBER}s/(.*)([0-9]+\.[0-9]+\.[0-9]+)(.*)/\1${VERSION}\3/g" "$FILE"
+                sed -i -E "${LINE_NUMBER}s/(.*)([0-9]+\.[0-9]+\.[0-9]+)(.*)/\1${VERSION}\3/g" "$FILE" || echo "sed failed"
             fi
         done
     fi
